### ISSUE TITLE
mass mem sensor

### ISSUE THREAD

**Issue by lucasromeiro** [bmrzycki/bt-temp-homebridge-http-webhooks#1]
Hi, how can I access ibs-th2 mass memory? (internal memory)
thanks

**Comment by bmrzycki** [comment]
Hello @lucasromeiro.

I'm sorry I don't know how to help you. I reverse engineered the BT advertisement data using a freezer and their iOS app. I don't access any of the more advanced features of the ibs-th2. In fact, I don't even pair to it and just read the advertisement broadcasts.

I wish you luck, there may be some other projects that do things with the internal memory of the th2.
